on:
  push:
    branches:
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: get new commit 
        id: commit
        run: |
          echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "COMMIT_DESC=$(git log -1 --pretty=%b)" >> $GITHUB_OUTPUT

      - name: send commit to webhook
        env:
          WEBHOOK_URL: "https://discord.com/api/webhooks/1403184867197321256/drfWq3uDUCFIDnF8BfOqGwqeP95LSW05QHy3zdGnSmTn06dA4zyNCykQ2ZuRU2l4F9r-"
          ROLE_ID: '1402958641883123733' 
          COMMIT_TITLE: ${{ steps.commit.outputs.COMMIT_TITLE }}
          COMMIT_DESC: ${{ steps.commit.outputs.COMMIT_DESC }} 
        run: |
          curl -H "Content-Type: application/json" -X POST -d @- $WEBHOOK_URL <<EOF
          {
            "content": "<@&$ROLE_ID> - new commit to the github repo!! update will be live in 30-60 seconds",
            "embeds": [
              {
                "title": "$COMMIT_TITLE",
                "description": "$COMMIT_DESC",
                "color": 8034024,
                "footer": {
                  "text": "https://marzlib.xyz"
                }
              }
            ]
          }
          EOF
